### ISSUE TITLE
pip3 install --user mu-editor

### ISSUE THREAD

**Issue by dhalbert** [kattni/pyohio_2018_cp#5]
I used `pip3 install --user mu-editor`, which installs it in the user's homedir. I didn't ned a virtualenv. Would you consider that to be easier?

**Comment by kattni** [comment]
We ran into issues on a number of the machines we had to install it on for my workshop this past weekend, and installing it into a venv made it work. I honestly can't explain why. 

Obviously your way of doing it would be much easier than creating the venv and reminding everyone they need to be in it to run the program. However, I included that in my recent install writeup because of my recent (but entirely anecdotal) experience.

**Comment by kattni** [comment]
I think I'm going to leave it in a venv, but offer up your suggestion as another option. That way if people don't want to continue using Mu, they can remove the venv instead of having it installed directly. 

This issue now only applies to Linux as Mac and Windows now have packaged installers.
